name: Qualité & Typage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy

      - name: Black format check
        run: black --check .

      - name: Flake8 lint
        run: flake8 .

      - name: MyPy type-check
        run: mypy .
